version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dmuba
      MONGO_INITDB_ROOT_PASSWORD: dmuba

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dmuba
      ME_CONFIG_MONGODB_ADMINPASSWORD: dmuba
